export const PERMISSIONS = {
  DASHBOARD_READ: 'dashboard.read',
  USER_CREATE: 'user.create',
  USER_READ: 'user.read',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  RECIPE_CREATE: 'recipe.create',
  RECIPE_READ: 'recipe.read',
  RECIPE_UPDATE: 'recipe.update',
  RECIPE_DELETE: 'recipe.delete',
  VALIDATION_CREATE: 'validation.create',
  VALIDATION_READ: 'validation.read',
  VALIDATION_DELETE: 'validation.delete',
  HACCP_READ: 'haccp.read',
  CUSTOMER_READ: 'customer.read',
  CUSTOMER_UPDATE: 'customer.update',
};
